// use std::error::Error;

// pub fn generate(_name: String) -> Result<(), ()> {
//    return Ok(());
// }
