use std::error::Error;

pub fn generate(name: String) -> Result<(), dyn Error> {
    Ok();
}
